name: Withdraw Bounty
description: Withdraw a bounty for an issue you solved.
title: Withdraw
labels: [withdraw]
body:
  - type: markdown
    attributes:
      value: |
        ### No address yet?
        
        To withdraw, you need to configure an address in your profile repository. That's a repository with a name that matches your GitHub username. [Create this repository](https://github.com/new) if you haven't done so already. Then add a cryptoactions.json file with the following content and fill in your address:

        ```
        {
          "ethereum": {
            "address": "0x..."
          }
        }
        ```

        You can change that address at any time.

        Alternatively you can add a "cryptoactions" section in a package.json file.

        ```
        "cryptoactions": {
          "ethereum": {
            "address": "0x..."
          }
        }
        ```

        That's it. Now enter the URL of the issue. If you are eligible to withdraw the bounty, it will be sent to your configured address immediately.
  - type: input
    id: issue
    attributes:
      label: Issue URL
      description: The URL of the Issue you solved.
      placeholder: https://github.com/.../.../issues/123
    validations:
      required: true
  - type: dropdown
    id: oraclefee
    attributes:
      label: Oracle Fee
      description: Top up the oracle with a percentage of your bounty.
      options:
        - 1 %
        - 5 %
        - 10 %
    validations:
      required: true