name: Withdraw Bounty
on:
  issues:
    types: [ opened ]

env:
  CONTRACT: "0x970bFa180549E0D07066915e560cea6Fb1958d69"

jobs:
  withdraw:
    name: Check eligability and release bounty
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'withdraw') }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: a3423c80c29490d4ddc051623a765c85f8402b7a
      
      - name: Check eligability
        uses: actions/github-script@v5
        id: eligibility
        with:
          script: |
            const checkEligibility = require('./.github/workflows/check-eligibility.js')
            return await checkEligibility(context, github)

      - name: Release bounty
        if: fromJSON(steps.eligibility.outputs.result)
        uses: web3actions/tx@bc0119599bd6377e4b4070722d77feb6f07986f8
        with:
          network: kovan
          infura-key: ${{ secrets.INFURA_KEY }}
          wallet-key: ${{ secrets.WALLET_KEY }}
          contract: ${{ env.CONTRACT }}
          function: "withdraw(string,address,uint256,bytes)"
          inputs: '["${{ fromJSON(github.event.issue.body).issueId }}", "${{ fromJSON(github.event.issue.body).to }}"]'
          signer: web3actions/signer
          github-token: ${{ secrets.PAT }}
      
      - name: Comment success
        uses: actions/github-script@v5
        if: fromJSON(steps.eligibility.outputs.result)
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Withdrawal successful!'
            })
      
      - name: Comment failure
        uses: actions/github-script@v5
        if: ${{ !fromJSON(steps.eligibility.outputs.result) }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Withdrawal failed! You are not eligible to withdraw this bounty.'
            })