name: Withdrawal
on:
  issues:
    types: [ opened ]

env:
  CONTRACT: "0x94D1ca098e6B7eDDeC454D4EBE439646BF7238DD"

jobs:
  consecutiveness:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'withdraw') }}
    steps:
    - uses: mktcode/consecutive-workflow-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  withdrawal:
    name: Withdrawal
    needs: [ consecutiveness ]
    runs-on: ubuntu-latest
    steps:
      - uses: cryptoactions/tx@4c78a7a81a4b5b110e6e2791b3bfe910267a8a7e
        id: balance
        with:
          rpc-node: ${{ secrets.RPC_NODE }}
          contract: ${{ env.CONTRACT }}
          function: "getIssueBalance(string) returns(uint256)"
          inputs: "['${{ fromJSON(github.event.issue.body).issueId }}']"

      - run: echo "${{ steps.balance.outputs.result }}"